<html lang="{{ site.lang | default: "en-US" }}">
  <head>

{% seo %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#157878">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <link rel="stylesheet" href="{{ '/assets/css/style.css?v=' | append: site.github.build_revision | relative_url }}">
  </head>
  <body>

    <header class="page-header" role="banner">
      <h1 class="project-name">Simple Timer</h1>
      <h2 class="project-tagline">A Moddable 2 based timer - plug it in and it goes, tap the screen to reset</h2>

        <a href="https://github.com/mikehedman/simple-timer" class="btn">View on GitHub</a>

      {% if site.show_downloads %}
        <a href="{{ site.github.zip_url }}" class="btn">Download .zip</a>
        <a href="{{ site.github.tar_url }}" class="btn">Download .tar.gz</a>
      {% endif %}
    </header>

    <main id="content" class="main-content" role="main">

      <footer class="site-footer">
        <span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.</span>
      </footer>
    </main>
  </body>
</html>
